#!/usr/bin/env python3
# Generate a C/C++ icon header for one Phosphor weight from its web style.css.
# Source: @phosphor-icons/web@2.1.2  (https://github.com/phosphor-icons/web)
#
# Phosphor is not in juliettef/IconFontCppHeaders, and its weights do not share
# codepoints, so each bundled weight gets its own header generated here.
#
# Usage:
#   python gen_phosphor_icons.py --css <style.css> --out <Icons.h> \
#       --prefix PH --font Phosphor.ttf
#
# Emits ICON_<PREFIX>_<NAME> byte-string defines plus ICON_MIN_<PREFIX> /
# ICON_MAX_<PREFIX> range constants, mirroring the IconFontCppHeaders layout.

import argparse
import re

RULE = re.compile(r'ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"', re.S)


def utf8_escape(cp: int) -> str:
    return ''.join(f'\\x{b:02x}' for b in chr(cp).encode('utf-8'))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--css', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--prefix', required=True)   # PH (regular) / PHF (fill)
    ap.add_argument('--font', required=True)      # ttf filename shipped in assets
    ap.add_argument('--version', default='2.1.2')
    args = ap.parse_args()

    with open(args.css, encoding='utf-8') as f:
        css = f.read()

    icons = []  # (NAME, codepoint)
    for name, hexcp in RULE.findall(css):
        icons.append((name.upper().replace('-', '_'), int(hexcp, 16)))
    icons.sort(key=lambda x: x[0])

    cps = [cp for _, cp in icons]
    lo, hi = min(cps), max(cps)
    p = args.prefix

    out = []
    out.append(f'// Generated by scripts/tools/gen_phosphor_icons.py')
    out.append(f'// from @phosphor-icons/web@{args.version} ({args.font}). Do not edit by hand.')
    out.append('#pragma once')
    out.append('')
    out.append(f'#define FONT_ICON_FILE_NAME_{p} "{args.font}"')
    out.append('')
    out.append(f'#define ICON_MIN_{p} 0x{lo:04x}')
    out.append(f'#define ICON_MAX_{p} 0x{hi:04x}')
    out.append('')
    for name, cp in icons:
        out.append(f'#define ICON_{p}_{name} "{utf8_escape(cp)}"\t// U+{cp:04x}')
    out.append('')

    with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))

    print(f'{args.out}: {len(icons)} icons, range U+{lo:04x}..U+{hi:04x}')


if __name__ == '__main__':
    main()